<a href="https://colab.research.google.com/github/ChoccoCodes/ML/blob/main/Naive_Bayes_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np 
import pandas as pd

import sklearn 

import urllib. request as ur

In [4]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

In [5]:
from sklearn import metrics
#from sklearn.metrics import accuracy_score

In [8]:
from sklearn.metrics import accuracy_score
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"
raw_data = ur.urlopen(url)

In [9]:
dataset = np.loadtxt(raw_data, delimiter = ',')

print(dataset[0])

[  0.      0.64    0.64    0.      0.32    0.      0.      0.      0.
   0.      0.      0.64    0.      0.      0.      0.32    0.      1.29
   1.93    0.      0.96    0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.778   0.      0.
   3.756  61.    278.      1.   ]


In [10]:
print(dataset)

[[0.000e+00 6.400e-01 6.400e-01 ... 6.100e+01 2.780e+02 1.000e+00]
 [2.100e-01 2.800e-01 5.000e-01 ... 1.010e+02 1.028e+03 1.000e+00]
 [6.000e-02 0.000e+00 7.100e-01 ... 4.850e+02 2.259e+03 1.000e+00]
 ...
 [3.000e-01 0.000e+00 3.000e-01 ... 6.000e+00 1.180e+02 0.000e+00]
 [9.600e-01 0.000e+00 0.000e+00 ... 5.000e+00 7.800e+01 0.000e+00]
 [0.000e+00 0.000e+00 6.500e-01 ... 5.000e+00 4.000e+01 0.000e+00]]


In [11]:
x = dataset[:,0:48]
y = dataset[:,-1]

In [13]:
X_train, X_test, y_train,y_test = train_test_split(x,y,test_size = .33, random_state =17)

In [15]:
BernNB = BernoulliNB(binarize = True)
BernNB.fit(X_train, y_train)
print(BernNB)

BernoulliNB(binarize=True)


In [17]:
y_expect = y_test
y_pred = BernNB.predict(X_test)

print(accuracy_score(y_expect, y_pred))

0.8558262014483212


In [18]:
from sklearn.metrics import accuracy_score
print(accuracy_score([1,1,0], [1,0,1]))

0.3333333333333333


In [19]:
MultiNB = MultinomialNB()
MultiNB.fit(X_train, y_train)

y_pred = MultiNB.predict(X_test)
print(accuracy_score(y_expect, y_pred))

0.8736010533245556


In [20]:
GausNB = GaussianNB()
GausNB.fit(X_train, y_train)
y_pred = GausNB.predict(X_test)
print(accuracy_score(y_expect, y_pred))

0.8130348913759052
